version: '3'

services:
  go-common-tools-api:
    container_name: go-common-tools-api1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro  #实体机需要先执行   echo "Asia/Shanghai" > /etc/timezone 
      - /mydata/go/nengxing/go-common-tools-api:/go/src/app
      - /mydata/www/:/mydata/www/
    ports:
      - "9011:9011"
